### ISSUE TITLE
Error from pdf_sample.append()

### ISSUE THREAD

**Issue by cjhopp** [djpugh/MTfit#24]
krafla_axample.py now runs fine in parallel but, as it finishes, the following error is thrown:

```
Traceback (most recent call last):
  File "/home/chet/anaconda3/envs/mtfit_36/lib/python3.6/site-packages/mtfit-0+untagged.54.g931200b-py3.6-linux-x86_64.egg/mtfit/inversion.py", line 2485, in _random_sampling_forward
    MTs, end = self._parse_job_result(result)
  File "/home/chet/anaconda3/envs/mtfit_36/lib/python3.6/site-packages/mtfit-0+untagged.54.g931200b-py3.6-linux-x86_64.egg/mtfit/inversion.py", line 2804, in _parse_job_result
    return self.algorithm.iterate(job_result)
  File "/home/chet/anaconda3/envs/mtfit_36/lib/python3.6/site-packages/mtfit-0+untagged.54.g931200b-py3.6-linux-x86_64.egg/mtfit/algorithms/monte_carlo.py", line 103, in iterate
    self.pdf_sample.append(**result)
  File "/home/chet/anaconda3/envs/mtfit_36/lib/python3.6/site-packages/mtfit-0+untagged.54.g931200b-py3.6-linux-x86_64.egg/mtfit/sampling.py", line 88, in append
    elif not isinstance(ln_pdf, (float, long, int, np.float64, np.float32)) and moment_tensors.shape[1] != ln_pdf.shape[1]:
AttributeError: 'dict' object has no attribute 'shape'

--------
DC inversion complete, elapsed time: 184.96504020690918
Worker-1 Ending
```

This is Ubuntu 14.04, python 3.6. Haven't tried on py 2.7 yet.

**Comment by djpugh** [comment]
This may have been closed by #21/ #23, will check and see if I can repro

**Comment by djpugh** [comment]
(I have the examples running ok on windows, and have been doing a bit of fixing on the output code)

**Comment by cjhopp** [comment]
Just pulled down the new changes and testing again. Thanks!

**Comment by cjhopp** [comment]
Error persists with a new install of develop branch

**Comment by djpugh** [comment]
OK, I'm currently testing on windows and it seems ok, but I will test further tomorrow on linux as well

**Comment by djpugh** [comment]
Runs ok on Windows, so will test on linux tomorrow!

**Comment by cjhopp** [comment]
krafla_event.py runs perfectly on Py 2.7, so that's helpful!

**Comment by djpugh** [comment]
Fixed on python 3 too
